name: Auto Update
on:
  push:
    branches:
      - staging

jobs:
  autoupdate:
    name: Auto Update
    runs-on: ubuntu-20.04
    steps:
      - uses: chinthakagodawita/autoupdate@v1.6.0
        env:
          GITHUB_TOKEN: '${{ secrets.GIT_TOKEN }}'
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          MERGE_MSG: "Branch was auto-updated to staging."
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          PR_READY_STATE: "ready_for_review"
          MERGE_CONFLICT_ACTION: "ignore"

