name: Update stable tag to the newly added test cases
on:
  pull_request:
    types: [ closed ]
    branches: [main] #Used to manually trigger workflow

  workflow_dispatch:

jobs:
  upload-tags-workflow:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
        - uses: actions/checkout@v3
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: 2.6.6
            bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        - run: bundle exec ruby test.rb ${{ secrets.GIT_TOKEN }} ${{ secrets.FR_TOKEN }}
