name: Update stable tag to the newly added test cases
on:
  push:
    branches: [dummy] #Used to manually trigger workflow

  workflow_dispatch:

jobs:
  upload-tags-workflow:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ruby-version: 2.6.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
